# Generated by Django 4.2.23 on 2025-07-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_meeting_title_meeting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availabilityresponse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timeoption',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
